# Generated by Django 5.1.3 on 2024-12-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="post_images/default.png", upload_to="post_images/"
            ),
        ),
    ]
